# -----------------------------
#  Base image Python 3.10
# -----------------------------
FROM python:3.10-slim

# -----------------------------
#  System dependencies
# -----------------------------
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    python3-dev \
    libhdf5-dev \
    libblas-dev \
    liblapack-dev \
    gfortran \
    && rm -rf /var/lib/apt/lists/*

# -----------------------------
#  Application directory
# -----------------------------
WORKDIR /app

# -----------------------------
#  Installation des dépendances
# -----------------------------
COPY requirements.txt .

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# -----------------------------
#  Copy framework files
# -----------------------------
# 3. Maintenant on copie le reste du code.
# Si tu modifies AWSCTD.py, seule cette étape est refaite (très rapide).
COPY . .

# -----------------------------
#  Default entrypoint
# -----------------------------
ENTRYPOINT ["python", "AWSCTD.py"]